schema_version = "1.0.0"

id = "node_to_python"
version = "3.5.0"
name = "Node To Python"
tagline = "Turn node groups into Python code"
maintainer = "Brendan Parmer <brendanparmer+nodetopython@gmail.com>"
type = "add-on"

website = "https://github.com/BrendanParmer/NodeToPython"

tags = ["Development", "Compositing", "Geometry Nodes", "Material", "Node"]

blender_version_min = "4.2.0"

license = [
    "SPDX:GPL-3.0-or-later",
]

[permissions]
files = "Creates and writes to files in a user-specified directory"